---
name: "Mount It"
version: 1.2.1
slug: mountit
description: Automatically detect and mount USB/SATA drives, with optional Home Assistant network storage exposure
url: https://github.com/EnderDragonEP/HomeAssistant-Apps
arch:
  - armv7
  - aarch64
  - amd64
startup: initialize
boot: auto
init: false
hassio_api: true
hassio_role: admin
homeassistant_api: true
host_network: true
udev: true
kernel_modules: true
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_MODULE
full_access: true
apparmor: true
devicetree: false
advanced: true
options:
  mount_unlabeled: false
  automount_on_plugin: true
  specific_label: ""
  mount_location: media
  expose_network_storage: true
  hdd_idle_seconds: 0
  file_activity_detail: "off"
  folder_mounts: []
schema:
  mount_unlabeled: bool
  automount_on_plugin: bool
  specific_label: str?
  mount_location: list(media|share|backup)
  expose_network_storage: bool
  hdd_idle_seconds: int(0,)?
  file_activity_detail: list(off|basic|detailed)
  folder_mounts:
    - name: "match(^[A-Za-z0-9_]*$)?"
      drive: str
      folder: str
      location: list(media|share|backup)
homeassistant: 2025.4.0
backup: hot
timeout: 60
